# Use root/example as user/password credentials
version: '3.8'

services:
  mongo:
    image: mongo:bionic
    restart: always
    volumes:
       - ./persist:/data/db
    ports:
      - '27017-27019:27017-27019'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

